print("This is a program to calculate Simple Interest")
pa=float(input("Enter the value of principle amount : "))
rate=float(input("Enter the interest rate per annum : "))
time=float(input("Enter the tennure (in years) : "))

interest=(pa*rate*time)/100
print("The interest generated by your money in the given tennure is : ", interest)