print("This is a program to print table of a number given by the user.")
num1=int(input("Enter the Number : "))
print("Here is the number for the number : ", num1)
print(num1,"x 1 =", num1*1)
print(num1,"x 2 =", num1*2)
print(num1,"x 3 =", num1*3)
print(num1,"x 4 =", num1*4)
print(num1,"x 5 =", num1*5)
print(num1,"x 6 =", num1*6)
print(num1,"x 7 =", num1*7)
print(num1,"x 8 =", num1*8)
print(num1,"x 9 =", num1*9)
print(num1,"x 10 =", num1*10)