num1=int(input("Enter the value of first number, a : "))
num2=int(input("Enter the value of Second number, b : "))
print("Subtract : ", num1-num2)
print("Multiply : ", num1*num2)
print("Division : ", num1/num2)
print("Modulus : ", num1%num2)
print("Exponential : ", num1**num2)
print("Floor Division : ", num1//num2)
print("Is num1>num2 : ", num1>num2)
print("Is num1<num2 : ", num1<num2)
print("Is num1>=num2 : ", num1>=num2)
print("Is num1<=num2 : ", num1<=num2)
print("Is num1==num2 : ", num1==num2)